// export const OPEN_LOGIN = "OPEN_LOGIN";
// export const CLOSE_LOGIN = "CLOSE_LOGIN";

// export const OPEN_REGISTER = "OPEN_REGISTER";
// export const CLOSE_REGISTER = "CLOSE_REGISTER";

export const OPEN_GLOBAL_LOADING = "OPEN_GLOBAL_LOADING";
export const CLOSE_GLOBAL_LOADING = "CLOSE_GLOBAL_LOADING";

// export const OPEN_FILTER_LOADING = "OPEN_FILTER_LOADING";
// export const CLOSE_FILTER_LOADING = "CLOSE_FILTER_LOADING";
