export const GET_USERS_LIST = "GET_USERS_LIST";
export const GET_USERS_LIST_SUCCESS = "GET_USERS_LIST_SUCCESS";

export const GET_USERS_LIST_PAGINATION = "GET_USERS_LIST_PAGINATION";
export const GET_USERS_LIST_PAGINATION_SUCCESS =
  "GET_USERS_LIST_PAGINATION_SUCCESS";

export const ADD_USER = "ADD_USER";

export const EDIT_USER = "EDIT_USER";

export const CLOSE_USER_MODAL = "CLOSE_USER_MODAL";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const SUBMIT_ADD_USER = "SUBMIT_ADD_USER";

export const SUBMIT_EDIT_USER = "SUBMIT_EDIT_USER";

export const SEARCH_USER = "SEARCH_USER";
