export const REGISTER = "REGISTER";

export const LOG_IN = "LOG_IN";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";

export const LOG_OUT = "LOG_OUT";

export const GET_INFO_BOOKING_USER = "GET_INFO_BOOKING_USER";
export const GET_INFO_BOOKING_USER_SUCCESS = "GET_INFO_BOOKING_USER_SUCCESS";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
