export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";

export const GET_CINEMA_LIST = "GET_CINEMA_LIST";
export const GET_CINEMA_LIST_SUCCESS = "GET_CINEMA_LIST_SUCCESS";

export const GET_CINEMA_BRANCH = "GET_CINEMA_BRANCH";
export const GET_CINEMA_BRANCH_SUCCESS = "GET_CINEMA_BRANCH_SUCCESS";

export const GET_CINEMA_BRANCH_FIRST = "GET_CINEMA_BRANCH_FIRST";

export const GET_SHOWTIME_ALL = "GET_SHOWTIME_ALL";
export const GET_SHOWTIME_ALL_SUCCESS = "GET_SHOWTIME_ALL_SUCCESS";

export const GET_SHOWTIME_DETAIL = "GET_SHOWTIME_DETAIL";

export const FILTER_BY_MOVIE_NAME = "FILTER_BY_MOVIE_NAME";
export const FILTER_BY_MOVIE_NAME_SUCCESS = "FILTER_BY_MOVIE_NAME_SUCCESS";

export const FILTER_BY_MOVIE_CINEMA = "FILTER_BY_MOVIE_CINEMA";

export const FILTER_BY_MOVIE_DAY = "FILTER_BY_MOVIE_DAY";

export const CHANGE_SHOWTIME_CODE = "CHANGE_SHOWTIME_CODE";

export const GET_SEAT_LIST = "GET_SEAT_LIST";
export const GET_SEAT_LIST_SUCCESS = "GET_SEAT_LIST_SUCCESS";

export const CHOOSE_SEAT = "CHOOSE_SEAT";

export const BOOK_TICKET = "BOOK_TICKET";
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS";

export const GET_MOVIE_DETAIL_OFFICIAL = "GET_MOVIE_DETAIL_OFFICIAL";
export const GET_MOVIE_DETAIL_OFFICIAL_SUCCESS =
  "GET_MOVIE_DETAIL_OFFICIAL_SUCCESS";
